// <auto-generated> gr-satellites AO-40 FEC QA vectors (qa_ao40_fec_deframer.py), GPL-3.0 (Daniel Estevez).
namespace VE3NEA.SkyTlm.Tests.Fixtures
{
  /// <summary>
  /// The gr-satellites AO-40 FEC QA vector — an off-air AO-73 packet. The 5450 float soft symbols live
  /// beside the corpus as <c>Data/ao40_fec_qa_symbols.f32</c> (the block starts 129 symbols in);
  /// <see cref="Frame"/> is the 256-byte frame the reference chain recovers from them.
  /// </summary>
  public static class Ao40Vectors
  {
    /// <summary>File name of the raw soft-symbol vector under the test project's <c>Data</c> folder.</summary>
    public const string SymbolsFile = "ao40_fec_qa_symbols.f32";

    /// <summary>Symbol index where the distributed syncword begins in <see cref="SymbolsFile"/>.</summary>
    public const int SyncOffset = 129;

    public const string Frame =
      "8900000000000000001fcc00ce02d100000708090900000501010040132fc8f25c8f3423f3ba0b5d627451c7eafa694a9a9f0009efa01ff4a7ea4ac6" +
      "8f1140111e10f7013e206400d78bf8d794c893a82ada52a60e580ec80f4e011d205a00db94a8aa8a9813ac690aa6a810e610920fb80150206400d796" +
      "a8c18b4825aba9cace9d10760fc91055013a205a00d79729088c484fa96a5af2a410390f7b0f860149206400d79408d08ad82aad6a5a7eb40e530e9b" +
      "0eb70109205a00db99a8f28fe838afaa8ac29e0ede0f480e310131205a00ce9bc8ff88681bb26a5acaa70fc30e740e580134205a00d79b391b97b8c5" +
      "b02b3ad6b5016b006a029e0003201300";
  }
}
