using System.Linq;
using FluentAssertions;
using VE3NEA.SkyTlm.Telemetry;
using Xunit;

namespace VE3NEA.SkyTlm.Tests.Unit
{
  /// <summary>
  /// Structural checks for the FoxTelem-derived MESAT1 (MO-122, NORAD 60209) definition
  /// (<c>Definitions/mesat1.json</c>, generated by <c>tools/foxtelem_to_json.py</c>). There is no off-air
  /// MESAT1 capture yet, so this verifies the definition <i>parses</i>, dispatches on the header <c>type</c>
  /// byte, and walks a full frame without error — not decoded values. Replace/extend with a pinned
  /// regression once a real frame is available (see docs/telemetry_multisat_plan.md §12).
  /// </summary>
  public class MesatTelemetryStructureTests
  {
    [Fact]
    public void Definition_IsRegistered_ForNorad60209()
    {
      var def = new TelemetryRegistry().ForNorad(60209);
      def.Should().NotBeNull("mesat1.json lists norad 60209");
      def!.Dispatch.Should().NotBeNull();
      def.Dispatch!.Field.Should().Be("type");
      def.Dispatch.Cases.Should().HaveCount(9);           // Type0..Type8
    }

    [Theory]
    [InlineData(0, "realtime_1")]
    [InlineData(1, "realtime_2")]
    [InlineData(7, "diagnostic")]
    public void FrameTypeByte_DispatchesToExpectedLayout(int type, string layout)
    {
      var def = new TelemetryRegistry().ForNorad(60209)!;
      // 12-byte header + a generous payload; header byte 1 is the dispatch 'type'. Non-zero fill so
      // calibrated fields produce finite values through the walk.
      var bytes = Enumerable.Repeat((byte)0x55, 700).ToArray();
      bytes[1] = (byte)type;

      var rec = TelemetryParser.Parse(def, bytes);
      rec.Should().NotBeNull();
      rec!.Layout.Should().Be(layout);
      rec.Fields.Should().NotBeEmpty();
      // the header's uptime/resetCnt are visible telemetry and must survive the walk
      rec.Fields.Select(f => f.Name).Should().Contain("uptime");
    }
  }
}
