using System;
using System.IO;
using System.Linq;
using FluentAssertions;
using MathNet.Numerics;
using VE3NEA.SkyTlm.Core;
using VE3NEA.SkyTlm.IO;
using Xunit;

namespace VE3NEA.SkyTlm.Tests.Regression
{
  /// <summary>
  /// Per-flavor decode regression over the committed off-air corpus in <c>Data/Wav</c>. Each
  /// <c>&lt;flavor&gt;.wav</c> holds three average-SNR bursts (the median, not the best or the marginal,
  /// of one representative recording) cut with a 2 s noise margin and concatenated — generated by the
  /// CorpusBuilder from real SatNOGS recordings. Each case runs the production
  /// <see cref="StreamingPipeline"/> with the flavor's resolved <see cref="SignalParams"/> read from the
  /// <c>&lt;flavor&gt;.wav.json</c> sidecar and asserts all three bursts still produce a CRC-valid frame —
  /// catching any demod/deframe regression across the full FSK/GFSK/GMSK/BPSK family.
  /// </summary>
  [Trait("Category", "Regression")]
  public class CorpusDecodeTests
  {
    // each clip holds three average-SNR bursts, so the expected CRC-frame count is 3 — except gmsk_ax100_Suomi100,
    // whose strongest burst the production (DC-removed, z-only-split) detector fragments: the shape-matched
    // statistic spikes mid-burst at flat power and the step-up split treats that as a new signal, orphaning that
    // burst's frame into a sub-segment the shape gate rejects. So that clip currently re-decodes two of its three
    // bursts — a deliberate cost of the colored-noise-robust detector, tracked here at 2 rather than asserting 3.
    [Theory]
    [InlineData("fsk_hades_HADES-SA.wav", 3)]
    [InlineData("gfsk_ax25_g3ruh_AEPEX.wav", 3)]
    [InlineData("fsk_ax100_NUSHSat1.wav", 3)]
    [InlineData("gmsk_ax100_Suomi100.wav", 2)]
    [InlineData("gmsk_usp_SAKHACUBE-CHOLBON.wav", 3)]
    [InlineData("bpsk_coherent_9k6_TEVEL2-1.wav", 3)]
    [InlineData("bpsk_coherent_1k2_Eaglet1.wav", 3)]
    public void Flavor_DecodesExpectedBursts(string file, int expectedCrcFrames)
    {
      string path = Path.Combine(TestPaths.WavDir, file);
      File.Exists(path).Should().BeTrue($"corpus file {file} must be generated (run CorpusBuilder)");

      var (samples, fs) = WavIqReader.Read(path);
      // resolved params live next to the wav as <flavor>.wav.json (written by CorpusBuilder); SampleRate
      // is filled from the loaded wav. Both off-air BPSK passes are coherent (differential = false).
      var p = SignalParamsSidecar.Load(path + ".json") with { SampleRate = fs };

      int crcFrames = DecodeCrcFrames(samples, fs, p);
      crcFrames.Should().BeGreaterThanOrEqualTo(expectedCrcFrames,
        $"{file} holds currently-decoding bursts of {p.Modulation}/{p.Framing}");
    }

    private static int DecodeCrcFrames(Complex32[] samples, int fs, SignalParams p)
    {
      int crc = 0;
      using var sp = new StreamingPipeline(p, new StreamingOptions());
      sp.BurstDecoded += r => crc += r.Frames.Count(f => f.CrcValid == true);
      int block = Math.Max(1, (int)(0.1 * fs));
      for (int i = 0; i < samples.Length; i += block)
        sp.Push(samples.AsSpan(i, Math.Min(block, samples.Length - i)));
      sp.Flush();
      return crc;
    }
  }
}
